#include "../ChessLib/figures/king.h"
#include "../ChessLib/figures/bishop.h"
#include "../ChessLib/figures/pawn.h"
#include "../ChessLib/figures/knight.h"
#include "../ChessLib/figures/rook.h"
#include "../ChessLib/figures/queen.h"
#include "../ChessLib/figures/figure.h"